### ISSUE TITLE
Add to save

### ISSUE THREAD

**Issue by sirolele** [kevincobain2000/email_extractor#1]
I will like this script to result able to save to file.
Also if possible to save interval by internal not until it crawl all urls Eg. if we are to crawl 40,000 pages website. it will crawl all before it grep one email to file

**Comment by sirolele** [comment]
OK I only need it to have it saved to File. i dont want the print Please i need it urgently.

**Comment by sirolele** [comment]
can you please send me the full txt file. so i wont be confused

**Comment by kevincobain2000** [comment]
if you don't want anything to get printed on screen and just the file just add `-s` or `--silent` to the script

```
07/24/15 @10:07AM - pulkit.kathuria@Mac Pro ~/Downloads/email_extractor@master* python email_extractor.py -u http://ionicframework.com/ -f some.txt -s
```

**Comment by kevincobain2000** [comment]
Full file
https://github.com/kevincobain2000/email_extractor/blob/master/email_extractor.py

I ll update on pip later. for the time you can just just the above file

**Comment by sirolele** [comment]
Thanks  you so much. I appreciate

**Comment by sirolele** [comment]
Administrator@WIN-RQL68GPKHHD ~
$ cd /home

Administrator@WIN-RQL68GPKHHD /home
$ python email_extractor.py -u http://www.realestateagents-ga.com/ -f some.txt
usage: email_extractor.py [-h] [-l LIMIT] [-u URL]
email_extractor.py: error: unrecognized arguments: -f some.txt

Error i got on mine

**Comment by kevincobain2000** [comment]
You don't have the latest code
https://github.com/kevincobain2000/email_extractor/blob/master/email_extractor.py

replace your code on Linux

```
07/24/15 @10:26AM - pulkit.kathuria@Mac Pro ~/Downloads python email_extractor.py -u http://www.realestateagents-ga.com/ -f some.txt
python: can't open file 'email_extractor.py': [Errno 2] No such file or directory
07/24/15 @10:26AM - pulkit.kathuria@Mac Pro ~/Downloads wget https://raw.githubusercontent.com/kevincobain2000/email_extractor/master/email_extractor.py
--2015-07-24 10:26:46--  https://raw.githubusercontent.com/kevincobain2000/email_extractor/master/email_extractor.py
Resolving raw.githubusercontent.com... 103.245.222.133
Connecting to raw.githubusercontent.com|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6454 (6.3K) [text/plain]
Saving to: 'email_extractor.py'

100%[====================================================================================================================================================>] 6,454       --.-K/s   in 0s

2015-07-24 10:26:46 (280 MB/s) - 'email_extractor.py' saved [6454/6454]

07/24/15 @10:26AM - pulkit.kathuria@Mac Pro ~/Downloads python email_extractor.py -u http://www.realestateagents-ga.com/ -f some.txt
  http://www.realestateagents-ga.com/
  http://www.realestateagents-ga.com/component/users/?view=reset
```

**Comment by sirolele** [comment]
I want to donate next week to you. This software is open, free and the best ever found
