### ISSUE TITLE
Some page links are not traversed

### ISSUE THREAD

**Issue by jacksongoode** [kevincobain2000/email_extractor#6]
I found that an <a> tag on a page like:

```
<a href="Journal" rel="history">Journal</a>
```

Is not being traversed?

**Comment by jacksongoode** [comment]
I believe this might be due to the site being a SPA?

**Comment by kevincobain2000** [comment]
That’s a relative url. Will check. Thanks

**Comment by kevincobain2000** [comment]
Should be fixed by https://github.com/kevincobain2000/email_extractor/releases/tag/v2.8
