### ISSUE TITLE
[Feature request] Domain exclusion list

### ISSUE THREAD

**Issue by jacksongoode** [kevincobain2000/email_extractor#7]
It would be nice to have a way of excluding a list of URLs or base domains such that the crawler, if it comes to one of these domains, doesn't end up clicking through it and continuing the crawl.

This could be useful for sites that you know are not useful or valid for the search.

**Comment by kevincobain2000** [comment]
It only crawls urls that belong to the parent url. It doesn’t crawl third party urls.
