### ISSUE TITLE
[Feature request] Parse email templates and reform

### ISSUE THREAD

**Issue by jacksongoode** [kevincobain2000/email_extractor#8]
For example:
- email(at)domain(dot)com
- email[at]domain[dot]com
- first(dot)last(at)domain(dot)com

If the full text is being parsed for email matching then I think it would be good to match and then reform the email based on substitution.

**Comment by kevincobain2000** [comment]
User can do grep on the text file that is produced by this tool. I don’t think the tool needs to complicate things with this extra option.

**Comment by jacksongoode** [comment]
Oh? Just to make sure you didn't misunderstand the idea, what I'm proposing is a way to identify text that is intended to prevent the typical parsing of emails, like when folks substitute the @ symbol with "at" or "(at)".

Practically, I think this would mean extending your `ExtractEmailsFromText` to feature some common substitutions like "at" for @ and "dot" for .

**Comment by kevincobain2000** [comment]
I understand now. Yea, will do.
